services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: qstep
      POSTGRES_PASSWORD: qstep
      POSTGRES_DB: qstep
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    container_name: postgis-qstep
    volumes:
      - ./workshop_data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
