---

# Install the galaxy modules via ansible-galaxy collection install community.general

- hosts: multipass
  tasks:
    - name: Update and upgrade packages via apt 
      become: true
      apt:
        upgrade: "yes"
        update_cache: yes

    - name: Install any updates
      become: true
      apt:
        name: aptitude

    - name: Postgres and PostGIS
      become: true
      package:
        name: postgis
        state: present

    - name: Install libpq dev for posgis ansible modules
      become: true
      package:
        name: libpq-dev
        state: present

    - name: Install acl for nonprivilaged postgres user access
      become: true
      package:
        name: acl
        state: present

    - name: Create qstep group
      become: true
      group:
        name: qstep
        state: present

    # - name: set CIM user details
    #   become: true
    #   user:
    #     name: cim
    #     comment: CIM user
    #     group: sudo
    #     shell: /bin/bash
    #     password: "$6$oncetherewasaway$c8l1bYnCnRLbH4BEF5cBs7Lh8epAqeD.amZMcEtixuu2lqpFc1LTa/4Lw1ke79WayeLvXa7.QQBvuvAdJh7ou0"

    - name: QSTEP user
      become: true
      user:
        name: qstep
        comment: QSTEP user
        group: qstep
        shell: /bin/bash
        password: "$6$oncetherewasaway$5dL3SAEH74q6rqsKUXVwg3URUcVhxL7ozuwEr1tyyln7Et68r.6zDtPblOCmqlWS/TJZlQhtY1jtmEh3FvCUJ."

    # - name: Create syslink to the psql binary to prevent users accessing anything else
    #   become: true
    #   shell: ln -s /bin/psql /home/qstep/bin/

    # - name: Ensure qstep bashrc is immutable.
    #   become: true
    #   file:
    #     path: /home/qstep/.bashrc
    #     attr: i    

    - name: Pip available
      become: true
      apt:
        name: python3-pip

    - name: Get python package for managing postgis
      become: true
      pip:
        name: setuptools

    - name: Get python package for managing postgis
      become: true
      pip:
        name: psycopg2

    - name: drop a database
      postgresql_db:
        name: qstep
        encoding: UTF-8
        template: template0
        state: absent
      become_user: postgres
      become: yes

    - name: create a database
      postgresql_db:
        name: qstep
        encoding: UTF-8
        template: template0
        state: present
      become_user: postgres
      become: yes

    - name: Adds postgis extension to the database qstep
      community.postgresql.postgresql_ext:
        name: postgis
        db: qstep
      become_user: postgres
      become: yes

    - name: Create QSTEP user in Postgres with access to qstep database
      community.postgresql.postgresql_user:
        name: qstep
        password: "qstepdbuser"
        role_attr_flags: "SUPERUSER"
      become_user: postgres
      become: yes

    - name: Copy file with owner and permissions
      copy:
        src: ../datasets/qstep.sql
        dest: /tmp/qstep.sql

    - name: Importing qstep table
      become_user: postgres
      become: yes
      shell: psql qstep < /tmp/qstep.sql

# Extra time datasets (uncomment to run)
# Note: The demo-small-en-20170815.sql.zip file needs to be extracted first

    - name: deletes demo database if exists
      postgresql_db:
        name: demo
        encoding: UTF-8
        template: template0
        state: absent
      become_user: postgres
      become: yes

    - name: create demo database
      postgresql_db:
        name: demo
        encoding: UTF-8
        template: template0
        state: present
      become_user: postgres
      become: yes

    - name: deletes rentals database if exists
      postgresql_db:
        name: dvdrental
        encoding: UTF-8
        template: template0
        state: absent
      become_user: postgres
      become: yes

    - name: create rentals database
      postgresql_db:
        name: dvdrental
        encoding: UTF-8
        template: template0
        state: present
      become_user: postgres
      become: yes

    - name: Copy flights database file
      copy:
        src: ../datasets/demo-small-en-20170815.sql
        dest: /tmp/demo-small-en-20170815.sql

    - name: Copy dvd rental database file
      copy:
        src: ../datasets/dvdrental.sql
        dest: /tmp/dvdrental.sql

    - name: Importing flights database
      become_user: postgres
      become: yes
      shell: psql demo < /tmp/demo-small-en-20170815.sql

    - name: Importing dvdrentals database
      become_user: postgres
      become: yes
      shell: psql dvdrental < /tmp/dvdrental.sql

